/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Profile {
  'name' : string,
  'accountNumber' : string,
  'phone' : string,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'status' : string,
  'recipient' : string,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface _SERVICE {
  'addMoney' : ActorMethod<[bigint], undefined>,
  'changePin' : ActorMethod<[string, string], boolean>,
  'getBalance' : ActorMethod<[], bigint>,
  'getProfile' : ActorMethod<[], Profile>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'hasPin' : ActorMethod<[], boolean>,
  'makePayment' : ActorMethod<[bigint, string, string], undefined>,
  'rechargeMobile' : ActorMethod<[bigint, string, string, string], undefined>,
  'setPin' : ActorMethod<[string], boolean>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
  'verifyPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];