/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Profile = IDL.Record({
  'name' : IDL.Text,
  'accountNumber' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'recipient' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  'addMoney' : IDL.Func([IDL.Int], [], []),
  'changePin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'hasPin' : IDL.Func([], [IDL.Bool], ['query']),
  'makePayment' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [], []),
  'rechargeMobile' : IDL.Func([IDL.Int, IDL.Text, IDL.Text, IDL.Text], [], []),
  'setPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'verifyPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Profile = IDL.Record({
    'name' : IDL.Text,
    'accountNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'recipient' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    'addMoney' : IDL.Func([IDL.Int], [], []),
    'changePin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'hasPin' : IDL.Func([], [IDL.Bool], ['query']),
    'makePayment' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [], []),
    'rechargeMobile' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'verifyPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };